export interface ScreenData {
  screen_name: string;
  assigned_category: string;
  confidence: number;
  match_method: string;
  match_detail: string;
}

export const screensData: ScreenData[] = [
  { screen_name: "panel-item-header-title", assigned_category: "Misc / Utilities / For Later Release", confidence: 1.0, match_method: "rule", match_detail: "panel-item-header-title" },
  { screen_name: "About HERDMind (not logged in)", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "herdmind" },
  { screen_name: "About HERDMind®", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "herdmind" },
  { screen_name: "All HERDMind Only Posts", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "posts" },
  { screen_name: "All HERDSter Only Posts", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "posts" },
  { screen_name: "All Set Up", assigned_category: "Uncategorized", confidence: 0.0, match_method: "none", match_detail: "" },
  { screen_name: "Annual Log Update Screen", assigned_category: "Misc / Utilities / For Later Release", confidence: 0.75, match_method: "fuzzy_medium", match_detail: "add screen" },
  { screen_name: "Annual Membership Pricing", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "membership pricing" },
  { screen_name: "Annual Membership Pricing HERDGM", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "membership pricing" },
  { screen_name: "Annual Membership Pricing HERDSG", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "membership pricing" },
  { screen_name: "Annual Membership Pricing Release 2", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "membership pricing" },
  { screen_name: "Annual Membership Pricing Transition", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "membership pricing" },
  { screen_name: "Articles Library Categories", assigned_category: "Content Library / Media", confidence: 1.0, match_method: "rule", match_detail: "articles" },
  { screen_name: "Articles List", assigned_category: "Content Library / Media", confidence: 1.0, match_method: "rule", match_detail: "articles" },
  { screen_name: "Auto Renewal", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "auto renewal" },
  { screen_name: "Block User Confirmed", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "block user" },
  { screen_name: "Block User HERDMind Comment", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comment" },
  { screen_name: "Block User HERDMind Post", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "Block User HERDster Comment", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comment" },
  { screen_name: "Block User HERDster Post", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "Blocked Users", assigned_category: "Administration / Management", confidence: 1.0, match_method: "rule", match_detail: "blocked users" },
  { screen_name: "Bookmarks Feed", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "bookmarks feed" },
  { screen_name: "Bookmarks Feed (HERDster)", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "bookmarks feed" },
  { screen_name: "Build Your Network", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "build your network" },
  { screen_name: "Cancel Stripe Checkout", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "cancel" },
  { screen_name: "Cancel Subscription", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "cancel" },
  { screen_name: "Change Password", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "change password" },
  { screen_name: "Chat Invitation", assigned_category: "Chat & Messaging", confidence: 1.0, match_method: "rule", match_detail: "chat" },
  { screen_name: "Chat Screen", assigned_category: "Chat & Messaging", confidence: 1.0, match_method: "rule", match_detail: "chat" },
  { screen_name: "ChatBot Conversation", assigned_category: "Chat & Messaging", confidence: 0.7272727272727272, match_method: "fuzzy_medium", match_detail: "conversations" },
  { screen_name: "Child Comment HERDMind", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comment" },
  { screen_name: "Child Comment HERDMind 2", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comment" },
  { screen_name: "Child Comment HERDster", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comment" },
  { screen_name: "Child Comment HERDster  2", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comment" },
  { screen_name: "ChoicePoint Games", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "choicepoint" },
  { screen_name: "Community Forum Guidelines", assigned_category: "Onboarding & Help", confidence: 1.0, match_method: "rule", match_detail: "community forum guidelines" },
  { screen_name: "Community Forum Welcome Page new", assigned_category: "Onboarding & Help", confidence: 1.0, match_method: "rule", match_detail: "welcome" },
  { screen_name: "Contact Us", assigned_category: "Onboarding & Help", confidence: 1.0, match_method: "rule", match_detail: "contact us" },
  { screen_name: "Conversations List", assigned_category: "Chat & Messaging", confidence: 1.0, match_method: "rule", match_detail: "conversations" },
  { screen_name: "Create Secure Password", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "create secure password" },
  { screen_name: "Delete Account Confirmation", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "delete account" },
  { screen_name: "Delete Chat Modal", assigned_category: "Chat & Messaging", confidence: 1.0, match_method: "rule", match_detail: "chat" },
  { screen_name: "Delete HERDMind Comment", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comment" },
  { screen_name: "Delete HERDMind Post", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "Delete HERDster Comment", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comment" },
  { screen_name: "Delete HERDster Post", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "Detailed Session Plan", assigned_category: "Session Plans & Meetings", confidence: 1.0, match_method: "rule", match_detail: "session plan" },
  { screen_name: "Edit Post (HERDsters)", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "Edit Post HERDMind", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "Edit Profile Info", assigned_category: "Profiles & Settings", confidence: 1.0, match_method: "rule", match_detail: "profile" },
  { screen_name: "Edit Profile Pic", assigned_category: "Profiles & Settings", confidence: 1.0, match_method: "rule", match_detail: "profile" },
  { screen_name: "Edit Topic", assigned_category: "Uncategorized", confidence: 0.0, match_method: "none", match_detail: "" },
  { screen_name: "Email Sign Up Release 1.0", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "sign up" },
  { screen_name: "Favorite Session Plan Details", assigned_category: "Session Plans & Meetings", confidence: 1.0, match_method: "rule", match_detail: "session plan" },
  { screen_name: "Favorite Sessions", assigned_category: "Session Plans & Meetings", confidence: 1.0, match_method: "rule", match_detail: "favorite sessions" },
  { screen_name: "Field Theory Ending A", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Ending B", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Ending C", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Ending D", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Ending E", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Ending F", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Ending G", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  10", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  11", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  12", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  13", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  14", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  15", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  16", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  17", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  18", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  19", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  2", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  20", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  21", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  22", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  23", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  24", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  3", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  4", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  5", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  6", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  7", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  8", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen  9", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "Field Theory Screen 1", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "field theory" },
  { screen_name: "For later Release", assigned_category: "Misc / Utilities / For Later Release", confidence: 1.0, match_method: "rule", match_detail: "for later release" },
  { screen_name: "Forgot Password Reset Catch", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "forgot password" },
  { screen_name: "Forgot Password Screen  3", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "forgot password" },
  { screen_name: "Free Overview", assigned_category: "Uncategorized", confidence: 0.0, match_method: "none", match_detail: "" },
  { screen_name: "Game Style 1 Ending A", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 1 Ending B", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 1 Ending C", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 1 Ending D", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 1 Scene 1", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Ending A", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Ending B", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Ending C", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Ending D", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene  1", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene  2", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene  21", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene  22", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene  23", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene  3", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene  4", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene  6", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 10", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 11", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 12", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 13", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 14", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 15", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 16", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 17", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 18", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 19", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 20", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 5", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 7", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 8", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style 2 Scene 9", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  10", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  11", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  12", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  13", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  14", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  15", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  17", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  18", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  19", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  20", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  21", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  22", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  23", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  3", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  4", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  5", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  6", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  7", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  8", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene  9", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene 16", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Game Style Scene 2", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "game style" },
  { screen_name: "Games for later release", assigned_category: "Games & Interactive Flow", confidence: 1.0, match_method: "rule", match_detail: "games for later release" },
  { screen_name: "HERD Affiliation (Profile Edit)", assigned_category: "Profiles & Settings", confidence: 1.0, match_method: "rule", match_detail: "profile" },
  { screen_name: "HERD Affiliation?", assigned_category: "Profiles & Settings", confidence: 1.0, match_method: "rule", match_detail: "herd affiliation" },
  { screen_name: "HERD Members Only Topics", assigned_category: "Uncategorized", confidence: 0.0, match_method: "none", match_detail: "" },
  { screen_name: "HERDMind Community Topics", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "herdmind" },
  { screen_name: "Hidden Posts", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "posts" },
  { screen_name: "Hidden Replies", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "hidden replies" },
  { screen_name: "Hidden Replies  to Replies", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "hidden replies" },
  { screen_name: "Home", assigned_category: "Misc / Utilities / For Later Release", confidence: 1.0, match_method: "fuzzy_high", match_detail: "home android" },
  { screen_name: "Home Android Version 0.23", assigned_category: "Misc / Utilities / For Later Release", confidence: 1.0, match_method: "rule", match_detail: "home android" },
  { screen_name: "Home Apple Version 0.0.23", assigned_category: "Misc / Utilities / For Later Release", confidence: 1.0, match_method: "rule", match_detail: "home apple" },
  { screen_name: "Home WPA", assigned_category: "Misc / Utilities / For Later Release", confidence: 1.0, match_method: "rule", match_detail: "wpa" },
  { screen_name: "How To Play ChoicePoints Games", assigned_category: "Onboarding & Help", confidence: 1.0, match_method: "rule", match_detail: "how to" },
  { screen_name: "How To Use Session Plans", assigned_category: "Session Plans & Meetings", confidence: 1.0, match_method: "rule", match_detail: "session plans" },
  { screen_name: "IAPHUB Check Error", assigned_category: "IAP / Platform Checks", confidence: 1.0, match_method: "rule", match_detail: "iaphub" },
  { screen_name: "IAPHUB Check Subscription Screen (Sign up)", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "sign up" },
  { screen_name: "IAPHUB Check Subscription Screen Log in", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "log in" },
  { screen_name: "IAPHUB Check Transition Screen", assigned_category: "Modals, Confirmations & Transitions", confidence: 1.0, match_method: "rule", match_detail: "transition" },
  { screen_name: "IAPHUB Check Transition Screen  3", assigned_category: "Modals, Confirmations & Transitions", confidence: 1.0, match_method: "rule", match_detail: "transition" },
  { screen_name: "IAPHUB Check Transition Screen 2", assigned_category: "Modals, Confirmations & Transitions", confidence: 1.0, match_method: "rule", match_detail: "transition" },
  { screen_name: "IAPHUB Restore", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "restore" },
  { screen_name: "Interested in?", assigned_category: "Misc / Utilities / For Later Release", confidence: 1.0, match_method: "fuzzy_high", match_detail: "interested in?" },
  { screen_name: "Loading Screen", assigned_category: "Misc / Utilities / For Later Release", confidence: 1.0, match_method: "rule", match_detail: "loading" },
  { screen_name: "Log In", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "log in" },
  { screen_name: "Log In Transition Screen", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "log in" },
  { screen_name: "Manage Subscription Modal", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "subscription" },
  { screen_name: "Message Received", assigned_category: "Chat & Messaging", confidence: 1.0, match_method: "rule", match_detail: "message" },
  { screen_name: "Monthly Log Update Screen", assigned_category: "Misc / Utilities / For Later Release", confidence: 0.75, match_method: "fuzzy_medium", match_detail: "add screen" },
  { screen_name: "Monthly Membership Pricing", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "membership pricing" },
  { screen_name: "Monthly Membership Pricing  HERDSG", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "membership pricing" },
  { screen_name: "Monthly Membership Pricing HERDGM", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "membership pricing" },
  { screen_name: "Monthly Membership Pricing Release 2", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "membership pricing" },
  { screen_name: "More Modal", assigned_category: "Modals, Confirmations & Transitions", confidence: 1.0, match_method: "rule", match_detail: "modal" },
  { screen_name: "My Profile", assigned_category: "Profiles & Settings", confidence: 1.0, match_method: "rule", match_detail: "profile" },
  { screen_name: "New Chat Modal", assigned_category: "Chat & Messaging", confidence: 1.0, match_method: "rule", match_detail: "chat" },
  { screen_name: "New Post (HERDMind Only)", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "New Post (HERDsters)", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "New Session Request", assigned_category: "Session Plans & Meetings", confidence: 1.0, match_method: "rule", match_detail: "session request" },
  { screen_name: "New Session Request  2 (For release 1.2)", assigned_category: "Session Plans & Meetings", confidence: 1.0, match_method: "rule", match_detail: "session request" },
  { screen_name: "News Alerts", assigned_category: "Notifications & Alerts", confidence: 1.0, match_method: "rule", match_detail: "news alerts" },
  { screen_name: "Notifications List", assigned_category: "Notifications & Alerts", confidence: 1.0, match_method: "rule", match_detail: "notifications" },
  { screen_name: "Notifications List 2", assigned_category: "Notifications & Alerts", confidence: 1.0, match_method: "rule", match_detail: "notifications" },
  { screen_name: "Notifications Routing Screen", assigned_category: "Notifications & Alerts", confidence: 1.0, match_method: "rule", match_detail: "notifications" },
  { screen_name: "Paid Feature Only", assigned_category: "Misc / Utilities / For Later Release", confidence: 1.0, match_method: "rule", match_detail: "paid feature only" },
  { screen_name: "Parent Comments HERDMind", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comments" },
  { screen_name: "Parent Comments HERDMster", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comments" },
  { screen_name: "Payment Failed", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "payment failed" },
  { screen_name: "Pdf Generator", assigned_category: "Content Library / Media", confidence: 1.0, match_method: "rule", match_detail: "pdf generator" },
  { screen_name: "Plan Limit Reached Modal", assigned_category: "Modals, Confirmations & Transitions", confidence: 1.0, match_method: "rule", match_detail: "modal" },
  { screen_name: "Plan Limit Reached Modal Transition", assigned_category: "Modals, Confirmations & Transitions", confidence: 1.0, match_method: "rule", match_detail: "modal" },
  { screen_name: "Print Favorite Sessions", assigned_category: "Session Plans & Meetings", confidence: 1.0, match_method: "rule", match_detail: "favorite sessions" },
  { screen_name: "Report Comment (HERDMind)", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comment" },
  { screen_name: "Report Comment (HERDster)", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comment" },
  { screen_name: "Report Post (HERDMind)", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "Report Post (HERDster)", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "Report Submitted (HERDMind)", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "report" },
  { screen_name: "Report Submitted HERDster", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "report" },
  { screen_name: "Request Result", assigned_category: "Uncategorized", confidence: 0.0, match_method: "none", match_detail: "" },
  { screen_name: "Restored Success", assigned_category: "Modals, Confirmations & Transitions", confidence: 0.7058823529411765, match_method: "fuzzy_medium", match_detail: "success transition" },
  { screen_name: "Restored Success Transition", assigned_category: "Modals, Confirmations & Transitions", confidence: 1.0, match_method: "rule", match_detail: "success transition" },
  { screen_name: "Restored Success Transition 2", assigned_category: "Modals, Confirmations & Transitions", confidence: 1.0, match_method: "rule", match_detail: "success transition" },
  { screen_name: "Scope of Practice", assigned_category: "Onboarding & Help", confidence: 1.0, match_method: "rule", match_detail: "scope of practice" },
  { screen_name: "Session Ratings", assigned_category: "Session Plans & Meetings", confidence: 1.0, match_method: "rule", match_detail: "session ratings" },
  { screen_name: "Session Ratings 2", assigned_category: "Session Plans & Meetings", confidence: 1.0, match_method: "rule", match_detail: "session ratings" },
  { screen_name: "Setup Step  1", assigned_category: "Uncategorized", confidence: 0.0, match_method: "none", match_detail: "" },
  { screen_name: "Sign Up Release  2", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "sign up" },
  { screen_name: "Sign Up Release 1.0", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "sign up" },
  { screen_name: "Sign Up Transition", assigned_category: "Authentication & Account", confidence: 1.0, match_method: "rule", match_detail: "sign up" },
  { screen_name: "Small Print", assigned_category: "Profiles & Settings", confidence: 1.0, match_method: "rule", match_detail: "small print" },
  { screen_name: "Social Profile HERDMind Comments", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comments" },
  { screen_name: "Social Profile HERDMind Posts", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "posts" },
  { screen_name: "Social Profile HERDSter Comments", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "comments" },
  { screen_name: "Social Profile HERDster Posts", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "posts" },
  { screen_name: "Success Modal", assigned_category: "Modals, Confirmations & Transitions", confidence: 1.0, match_method: "rule", match_detail: "modal" },
  { screen_name: "Trial Ended Upgrade", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "trial" },
  { screen_name: "Unblock Request Confirmation", assigned_category: "Modals, Confirmations & Transitions", confidence: 1.0, match_method: "rule", match_detail: "confirmation" },
  { screen_name: "Upgrade Codes Modal", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "upgrade" },
  { screen_name: "Upgrade Prompt", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "upgrade" },
  { screen_name: "Upgrade Prompt Transition", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "upgrade" },
  { screen_name: "Video Categories", assigned_category: "Content Library / Media", confidence: 1.0, match_method: "rule", match_detail: "video" },
  { screen_name: "Video Categories (Release 2)", assigned_category: "Content Library / Media", confidence: 1.0, match_method: "rule", match_detail: "video" },
  { screen_name: "Video List", assigned_category: "Content Library / Media", confidence: 1.0, match_method: "rule", match_detail: "video" },
  { screen_name: "Video Viewer", assigned_category: "Content Library / Media", confidence: 1.0, match_method: "rule", match_detail: "video" },
  { screen_name: "View Article", assigned_category: "Content Library / Media", confidence: 1.0, match_method: "rule", match_detail: "article" },
  { screen_name: "View HERDMind Post Comments", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "View HERDster Post Comments", assigned_category: "Social / Community", confidence: 1.0, match_method: "rule", match_detail: "post" },
  { screen_name: "YOUR SUBSCRIPTION HAS ENDED", assigned_category: "Subscriptions & Billing", confidence: 1.0, match_method: "rule", match_detail: "subscription" },
  { screen_name: "Add Screen", assigned_category: "Misc / Utilities / For Later Release", confidence: 1.0, match_method: "rule", match_detail: "add screen" },
];

// Calculate stats
export function getScreensStats() {
  const total = screensData.length;
  const categories = new Set(screensData.map(d => d.assigned_category)).size;
  const confidences = screensData.map(d => d.confidence);
  const avgConfidence = (confidences.reduce((a, b) => a + b, 0) / total * 100).toFixed(1);
  const highConfidence = (screensData.filter(d => d.confidence >= 0.85).length / total * 100).toFixed(1);

  return {
    total,
    categories,
    avgConfidence,
    highConfidence,
  };
}

// Get unique categories
export function getUniqueCategories(): string[] {
  return [...new Set(screensData.map(d => d.assigned_category))].sort();
}

